<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: postgresql
  database: <%= PROJECT_NAME %>_development
  username: root
  password: 
  host: localhost
  encoding: utf8
  
test:
  adapter: postgresql
  database: <%= PROJECT_NAME %>_test
  username: root
  password: 
  host: localhost
  encoding: utf8
  
staging:
  adapter: postgresql
  database: <%= PROJECT_NAME %>_staging
  username: <%= PROJECT_NAME %>
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  
production:
  adapter: postgresql
  database: <%= PROJECT_NAME %>_production
  username: <%= PROJECT_NAME %>
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
