<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: postgresql
  database: moodswings_development
  #username: mike
  #password: 
  #host: localhost
  #encoding: utf8
  
test:
  adapter: postgresql
  database: moodswings_test
  #username: mike
  #password: 
  #host: localhost
  #encoding: utf8
  
staging:
  adapter: postgresql
  database: moodswings_staging
  username: moodswings_
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  
production:
  adapter: postgresql
  database: moodswings_production
  username: moodswings_
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
